# Generated by Django 2.0.4 on 2018-04-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=32)),
                ('outside_ip', models.CharField(max_length=32)),
                ('inside_ip', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=32)),
                ('cpu_num', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=32)),
                ('bandwidth', models.CharField(max_length=32)),
                ('risk', models.CharField(max_length=64)),
            ],
        ),
    ]
