# Generated by Django 2.0.4 on 2018-04-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cloud',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='cmdb.project'),
            preserve_default=False,
        ),
    ]
