# Generated by Django 2.0.4 on 2018-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.BooleanField(),
        ),
    ]
