# Generated by Django 2.0.4 on 2018-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20180517_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.BooleanField(),
        ),
    ]
