# Generated by Django 2.0.4 on 2018-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20180517_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=64)),
                ('acc_mum', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
    ]
